### ISSUE TITLE
Start using Releases

### ISSUE THREAD

**Issue by xtrasmal** [claytonrcarter/tree-sitter-phpdoc#40]
Hi there,

When adding grammars, folks use specific commits to point to. Usually the commit of a release.

```toml
id = "php"
name = "PHP"
description = "PHP support."
version = "0.1.3"
schema_version = 1
authors = ["Piotr Osiewicz <piotr@zed.dev>"]
repository = "https://github.com/zed-industries/zed"

[language_servers.intelephense]
name = "Intelephense"
language = "PHP"
language_ids = { PHP = "php"}

[language_servers.phpactor]
name = "Phpactor"
language = "PHP"

[grammars.php]
repository = "https://github.com/tree-sitter/tree-sitter-php"
commit = "a1e0befae61715d9e162529b3c2bfd961d183613"
path = "php"

[grammars.phpdoc]
repository = "https://github.com/claytonrcarter/tree-sitter-phpdoc"
commit = "1d0e255b37477d0ca46f1c9e9268c8fa76c0b3fc"
```

This is how Zed does it. It would be great to rely on a certain release :)
